On: 
  push:
  pull_requests:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install node.js 14.x
        uses: actions/setup-node@v4
        with: 
          node-version: 14.x
      - name: Install dependencies
        run: npm clean-install
