name: Build and Scan

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x

      - name: Install API dependencies
        working-directory: api
        run: npm install

      - name: Install Client dependencies
        working-directory: simply_vulnerable_react/client
        run: npm ci
        
